
name: Semgrep
on:
  pull_request:
  push:
    branches: [master, develop]

jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    env:
      INPUT_PUBLISHURL: https://dev.semgrep.dev
    steps:
      - uses: actions/checkout@master
      - name: Semgrep
        id: semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          generateSarif: "1"
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: 44
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
        if: always()